/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.subermarket;

import static com.mycompany.subermarket.Cashier.CalcSubTotal;
import static com.mycompany.subermarket.Cashier.CalcTax;
import static com.mycompany.subermarket.Cashier.CalcTotal;
import javax.swing.JOptionPane;

/**
 *
 * @author Al Abouzaid
 */
public  class  ViewGUI extends javax.swing.JFrame {
    int bananaNum, AppleNum,OrangeNum,CoconutNum;
    double bananaPrice, ApplePrice,OrangePrice,CoconutPrice,SubTotal,Taxs,Totals;
    Products banana =new Products(3.5);
    Products apple =new Products(5.5);
    Products orange =new Products(2);
    Products coconut =new Products(7.5);
    Cashier cashier1= new Cashier(89434,"Tony","El Haram","+894346658");
    Manager manager1 =new Manager(89481,"El-ZOZ","El Zmalak","+89481115");
    Customer customer1=new Customer(89545,"Marten","El Maady","+89545197");

   
    
    
    public  ViewGUI() {
        initComponents();
       
        Billbox.setEditable(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        front = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Mangerinfo = new javax.swing.JButton();
        Cashierinf = new javax.swing.JButton();
        Customerinfo = new javax.swing.JButton();
        Store = new javax.swing.JPanel();
        BananaCount = new javax.swing.JSpinner();
        Banana = new javax.swing.JLabel();
        Apple = new javax.swing.JLabel();
        Orange = new javax.swing.JLabel();
        Coconut = new javax.swing.JLabel();
        AppleCount = new javax.swing.JSpinner();
        CoconutCount = new javax.swing.JSpinner();
        OrangeCount = new javax.swing.JSpinner();
        bananaCost = new javax.swing.JLabel();
        AppleCost = new javax.swing.JLabel();
        OrangeCost = new javax.swing.JLabel();
        CoconutCost = new javax.swing.JLabel();
        Totalboard = new javax.swing.JPanel();
        Subtotal = new javax.swing.JLabel();
        vat = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        Calcutate = new javax.swing.JButton();
        New_bill = new javax.swing.JButton();
        SubtotalCost = new javax.swing.JLabel();
        TaxCost = new javax.swing.JLabel();
        TotalCost = new javax.swing.JLabel();
        Discount = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Billbox = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        front.setBackground(new java.awt.Color(105, 164, 46));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Al Abouzaid\\Documents\\NetBeansProjects\\SuberMarket\\src\\main\\java\\com\\mycompany\\subermarket\\ClassesImg\\supermarket.png")); // NOI18N
        jLabel17.setText("El- ZOZ SuperMarket");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\Al Abouzaid\\Documents\\NetBeansProjects\\SuberMarket\\src\\main\\java\\com\\mycompany\\subermarket\\ClassesImg\\wink-icon.png")); // NOI18N
        jLabel18.setText("Your order in blink");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\Al Abouzaid\\Documents\\NetBeansProjects\\SuberMarket\\src\\main\\java\\com\\mycompany\\subermarket\\ClassesImg\\facebook.png")); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Al Abouzaid\\Documents\\NetBeansProjects\\SuberMarket\\src\\main\\java\\com\\mycompany\\subermarket\\ClassesImg\\whatsapp.png")); // NOI18N

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\Al Abouzaid\\Documents\\NetBeansProjects\\SuberMarket\\src\\main\\java\\com\\mycompany\\subermarket\\ClassesImg\\instagram.png")); // NOI18N

        Mangerinfo.setBackground(new java.awt.Color(105, 164, 46));
        Mangerinfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Mangerinfo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Al Abouzaid\\Documents\\NetBeansProjects\\SuberMarket\\src\\main\\java\\com\\mycompany\\subermarket\\ClassesImg\\manager.png")); // NOI18N
        Mangerinfo.setText("Manager Info");
        Mangerinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MangerinfoActionPerformed(evt);
            }
        });

        Cashierinf.setBackground(new java.awt.Color(105, 164, 46));
        Cashierinf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Cashierinf.setIcon(new javax.swing.ImageIcon("C:\\Users\\Al Abouzaid\\Documents\\NetBeansProjects\\SuberMarket\\src\\main\\java\\com\\mycompany\\subermarket\\ClassesImg\\cashier.png")); // NOI18N
        Cashierinf.setText("Cashier Info");
        Cashierinf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashierinfActionPerformed(evt);
            }
        });

        Customerinfo.setBackground(new java.awt.Color(105, 164, 46));
        Customerinfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Customerinfo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Al Abouzaid\\Documents\\NetBeansProjects\\SuberMarket\\src\\main\\java\\com\\mycompany\\subermarket\\ClassesImg\\team.png")); // NOI18N
        Customerinfo.setText("Customer Info");
        Customerinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerinfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frontLayout = new javax.swing.GroupLayout(front);
        front.setLayout(frontLayout);
        frontLayout.setHorizontalGroup(
            frontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frontLayout.createSequentialGroup()
                .addComponent(Mangerinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cashierinf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Customerinfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frontLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(42, 42, 42))
        );
        frontLayout.setVerticalGroup(
            frontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frontLayout.createSequentialGroup()
                .addGroup(frontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(frontLayout.createSequentialGroup()
                        .addGroup(frontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Mangerinfo)
                            .addComponent(Cashierinf)
                            .addComponent(Customerinfo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17))
                    .addGroup(frontLayout.createSequentialGroup()
                        .addGroup(frontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        Store.setBackground(new java.awt.Color(93, 165, 212));
        Store.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Store", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        BananaCount.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        BananaCount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BananaCountStateChanged(evt);
            }
        });

        Banana.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Banana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Banana.setText("Banana");

        Apple.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Apple.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Apple.setText("Apple");

        Orange.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Orange.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Orange.setText("Orange");

        Coconut.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Coconut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Coconut.setText("Coconut");

        AppleCount.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        AppleCount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AppleCountStateChanged(evt);
            }
        });

        CoconutCount.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        CoconutCount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CoconutCountStateChanged(evt);
            }
        });

        OrangeCount.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        OrangeCount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                OrangeCountStateChanged(evt);
            }
        });

        bananaCost.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bananaCost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bananaCost.setText("0.0 $");

        AppleCost.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        AppleCost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AppleCost.setText("0.0 $");

        OrangeCost.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        OrangeCost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OrangeCost.setText("0.0 $");

        CoconutCost.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CoconutCost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CoconutCost.setText("0.0 $");

        javax.swing.GroupLayout StoreLayout = new javax.swing.GroupLayout(Store);
        Store.setLayout(StoreLayout);
        StoreLayout.setHorizontalGroup(
            StoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StoreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StoreLayout.createSequentialGroup()
                        .addComponent(BananaCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Banana, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bananaCost, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StoreLayout.createSequentialGroup()
                        .addComponent(AppleCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Apple, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AppleCost, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(StoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StoreLayout.createSequentialGroup()
                        .addComponent(OrangeCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Orange, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StoreLayout.createSequentialGroup()
                        .addComponent(CoconutCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Coconut, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(StoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrangeCost, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CoconutCost, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        StoreLayout.setVerticalGroup(
            StoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StoreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BananaCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Banana)
                    .addComponent(Orange)
                    .addComponent(OrangeCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bananaCost)
                    .addComponent(OrangeCost))
                .addGap(28, 28, 28)
                .addGroup(StoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AppleCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apple)
                    .addComponent(CoconutCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Coconut)
                    .addComponent(AppleCost)
                    .addComponent(CoconutCost))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Totalboard.setBackground(new java.awt.Color(204, 204, 204));
        Totalboard.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        Subtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Subtotal.setText("SubTotal:");

        vat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        vat.setText("Tax: ");

        Total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Total.setText("Total: ");

        Save.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Save.setForeground(new java.awt.Color(105, 164, 46));
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Calcutate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Calcutate.setForeground(new java.awt.Color(105, 164, 46));
        Calcutate.setText("Calculate");
        Calcutate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcutateActionPerformed(evt);
            }
        });

        New_bill.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        New_bill.setForeground(new java.awt.Color(105, 164, 46));
        New_bill.setText("New bill");
        New_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_billActionPerformed(evt);
            }
        });

        SubtotalCost.setBackground(new java.awt.Color(255, 255, 255));
        SubtotalCost.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SubtotalCost.setText("0.0$");

        TaxCost.setBackground(new java.awt.Color(255, 255, 255));
        TaxCost.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TaxCost.setText("0.0$");

        TotalCost.setBackground(new java.awt.Color(255, 255, 255));
        TotalCost.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TotalCost.setText("0.0$");

        javax.swing.GroupLayout TotalboardLayout = new javax.swing.GroupLayout(Totalboard);
        Totalboard.setLayout(TotalboardLayout);
        TotalboardLayout.setHorizontalGroup(
            TotalboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TotalboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Calcutate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TotalboardLayout.createSequentialGroup()
                        .addGroup(TotalboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Subtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(TotalboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubtotalCost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalCost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TaxCost)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TotalboardLayout.createSequentialGroup()
                        .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(New_bill)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        TotalboardLayout.setVerticalGroup(
            TotalboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalboardLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(TotalboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Subtotal)
                    .addComponent(SubtotalCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TotalboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vat)
                    .addComponent(TaxCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TotalboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Total)
                    .addComponent(TotalCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Calcutate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(TotalboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save)
                    .addComponent(New_bill))
                .addContainerGap())
        );

        Discount.setBackground(new java.awt.Color(204, 204, 204));
        Discount.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Discount", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Total > 200  discount percentage 10% ");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Total > 500  discount percentage 15% ");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Total > 1000  discount percentage 25% ");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Total > 2000  discount percentage 30% ");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Thank you for visit our store");

        javax.swing.GroupLayout DiscountLayout = new javax.swing.GroupLayout(Discount);
        Discount.setLayout(DiscountLayout);
        DiscountLayout.setHorizontalGroup(
            DiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DiscountLayout.createSequentialGroup()
                .addGroup(DiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiscountLayout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addGroup(DiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiscountLayout.createSequentialGroup()
                        .addGroup(DiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiscountLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174))))
        );
        DiscountLayout.setVerticalGroup(
            DiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DiscountLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BIll", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        Billbox.setColumns(20);
        Billbox.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        Billbox.setRows(5);
        jScrollPane1.setViewportView(Billbox);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Store, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(front, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Totalboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(front, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Store, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Totalboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CalcutateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcutateActionPerformed

  SubTotal=  CalcSubTotal(bananaPrice,ApplePrice,OrangePrice,CoconutPrice);
    SubtotalCost.setText(SubTotal + "$");
    Taxs= CalcTax(SubTotal);
    TaxCost.setText(Taxs+"$");
    Totals= CalcTotal(SubTotal,Taxs);
    TotalCost.setText(Totals+"$");
    }//GEN-LAST:event_CalcutateActionPerformed

    private void BananaCountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BananaCountStateChanged
    bananaNum =(Integer) BananaCount.getValue(); 
    
    bananaPrice= banana.getPrice()* bananaNum;
    bananaCost.setText(bananaPrice +"$");
    
    }//GEN-LAST:event_BananaCountStateChanged

    private void AppleCountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AppleCountStateChanged
    AppleNum =(Integer) AppleCount.getValue(); 
    
    ApplePrice= apple.getPrice()* AppleNum;
    AppleCost.setText(ApplePrice +"$");        // TODO add your handling code here:
    }//GEN-LAST:event_AppleCountStateChanged

    private void OrangeCountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_OrangeCountStateChanged
    OrangeNum =(Integer) OrangeCount.getValue(); 
    
    OrangePrice= orange.getPrice()* OrangeNum;
    OrangeCost.setText(OrangePrice +"$");         // TODO add your handling code here:
    }//GEN-LAST:event_OrangeCountStateChanged

    private void CoconutCountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CoconutCountStateChanged
        CoconutNum =(Integer) CoconutCount.getValue(); 
    
    CoconutPrice= coconut.getPrice()* CoconutNum;
    CoconutCost.setText(CoconutPrice +"$");     
     
    }//GEN-LAST:event_CoconutCountStateChanged

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        Billbox.setText(".....................................\n"+
     "\t   El-ZOZ SuperMarket\n"
    +"Cashier ID:"+cashier1.getID()+"\n"
    +"Cashier Name:"+cashier1.getName()+"\n"
    +"....................................."+"\n"
    +"SubTotal\t\t\t"+SubTotal+"$\n"
    +"Taxs\t\t\t\t"+Taxs+"$\n"
    +"Totals\t\t\t\t"+Totals+"$\n"
    +"....................................."+"\n"
    +"\t\t\t   Thank you");

    }//GEN-LAST:event_SaveActionPerformed

    private void New_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_billActionPerformed
        Billbox.setText("");
        SubtotalCost.setText("0.0$");
        TaxCost.setText("0.0$");
   
        TotalCost.setText("0.0 $");
        bananaCost.setText("0.0 $");
        AppleCost.setText("0.0 $");  
        OrangeCost.setText("0.0 $");
        CoconutCost.setText("0.0 $");  
        CoconutCount.setValue(0);
        OrangeCount.setValue(0);
        AppleCount.setValue(0);
        BananaCount.setValue(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_New_billActionPerformed

    private void MangerinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MangerinfoActionPerformed

        JOptionPane.showMessageDialog(null, ""+manager1.toString());

    }//GEN-LAST:event_MangerinfoActionPerformed

    private void CashierinfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashierinfActionPerformed
        JOptionPane.showMessageDialog(null, ""+cashier1.toString());
    }//GEN-LAST:event_CashierinfActionPerformed

    private void CustomerinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerinfoActionPerformed
        JOptionPane.showMessageDialog(null, ""+customer1.toString());
    }//GEN-LAST:event_CustomerinfoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ViewGUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apple;
    private javax.swing.JLabel AppleCost;
    private javax.swing.JSpinner AppleCount;
    private javax.swing.JLabel Banana;
    private javax.swing.JSpinner BananaCount;
    private javax.swing.JTextArea Billbox;
    private javax.swing.JButton Calcutate;
    private javax.swing.JButton Cashierinf;
    private javax.swing.JLabel Coconut;
    private javax.swing.JLabel CoconutCost;
    private javax.swing.JSpinner CoconutCount;
    private javax.swing.JButton Customerinfo;
    private javax.swing.JPanel Discount;
    private javax.swing.JButton Mangerinfo;
    private javax.swing.JButton New_bill;
    private javax.swing.JLabel Orange;
    private javax.swing.JLabel OrangeCost;
    private javax.swing.JSpinner OrangeCount;
    private javax.swing.JButton Save;
    private javax.swing.JPanel Store;
    private javax.swing.JLabel Subtotal;
    private javax.swing.JLabel SubtotalCost;
    private javax.swing.JLabel TaxCost;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel TotalCost;
    private javax.swing.JPanel Totalboard;
    private javax.swing.JLabel bananaCost;
    private javax.swing.JPanel front;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel vat;
    // End of variables declaration//GEN-END:variables
}
